plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/tylermartin/Dropbox/Code/envelope-email"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "https://github.com/tymrtn/U1F4E7"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]